# Simple demo Rakefile to autorun samples in current directory
# adjust path to k9 executable, and or opts as required

desc 'run demo'
task default: [:demo]

desc 'demo'
task :demo do
  samples_list.shuffle.each { |sample| run_sample sample }
end

def samples_list
  Dir.glob('*.rb').map { |file| File.join(__dir__, file) }
end

def run_sample(sample_name)
  puts "Running #{sample_name}...quit to run next sample"
  system "jruby --dev -S k9 -r #{sample_name}"
end
